all:
  children:
    ydb_cluster:
      hosts:
        redos-cert-ydb1:
          node_id: 1
          data_center: 'zone-a'
          rack: '1'
          ansible_host: 192.168.62.17
          ansible_user: root
          ansible_ssh_private_key_file: /root/.ssh/id_isup_cbt
        redos-cert-ydb2:
          node_id: 2
          data_center: 'zone-b'
          rack: '2'
          ansible_host: 192.168.62.18
          ansible_user: root
          ansible_ssh_private_key_file: /root/.ssh/id_isup_cbt
        redos-cert-ydb3:
          node_id: 3
          data_center: 'zone-c'
          rack: '3'
          ansible_host: 192.168.62.19
          ansible_user: root
          ansible_ssh_private_key_file: /root/.ssh/id_isup_cbt
    # postgres_cluster:
    #   hosts:
    #     centos-cert1:
    #       ansible_host: 192.168.88.13
    #       ansible_user: root
    #       ansible_ssh_private_key_file: /root/.ssh/id_isup_cbt
    #     centos-cert2:
    #       ansible_host: 192.168.88.14
    #       ansible_user: root
    #       ansible_ssh_private_key_file: /root/.ssh/id_isup_cbt
    #     centos-cert3:
    #       ansible_host: 192.168.88.15
    #       ansible_user: root
    #       ansible_ssh_private_key_file: /root/.ssh/id_isup_cbt
