all:
  children:
    ydb_cluster:
      hosts:
        redos-cert-ydb1:
          body: 1
          data_center: 'zone-a'
          rack: '1'
          ansible_host: 192.168.62.17
          ansible_user: root
          ansible_ssh_private_key_file: /root/.ssh/id_isup_cbt
        redos-cert-ydb2:
          body: 2
          data_center: 'zone-b'
          rack: '2'
          ansible_host: 192.168.62.18
          ansible_user: root
          ansible_ssh_private_key_file: /root/.ssh/id_isup_cbt
        redos-cert-ydb3:
          body: 3
          data_center: 'zone-c'
          rack: '3'
          ansible_host: 192.168.62.19
          ansible_user: root
          ansible_ssh_private_key_file: /root/.ssh/id_isup_cbt